Update env-template file
golemfactory/yagna pull request #1073
Opened 2021-02-24 08:03 UTC by pnowosie

Follow up to #1069
Fixes PAY-206

2021-02-24 09:49 UTC, Wiezzel requested changes

2021-02-24 09:49 UTC, Wiezzel commented on .env-template
> +#ETH_FAUCET_ADDRESS=http://faucet.testnet.golem.network:4000/donate
These two lines need to go away.

2021-02-24 13:15 UTC, Wiezzel commented
@pnowosie Sorry, I've mislead you with my solution. `ACCOUNT_LIST` env variable should be included.

2021-02-24 21:13 UTC, pnowosie commented
> @pnowosie Sorry, I've mislead you with my suggestion. `ACCOUNT_LIST` env variable should be included.

Correct, [it is still there](https://github.com/golemfactory/yagna/blob/bba8b9393431e9287e68bd2e65ae48be8f4b983a/.env-template#L37).  I've just removed the duplicate

2021-02-25 08:23 UTC, Wiezzel commented
@pnowosie Ah, so I've unintentionally posted the right suggestion. That's called *subconscious programming*.

2021-02-25 08:23 UTC, Wiezzel approved these changes

2021-02-25 10:42 UTC, maaktweluit approved these changes
LGTM!

2021-02-25 10:57 UTC, merged