Additional market broadcast metrics
golemfactory/yagna pull request #1288
Opened 2021-04-29 16:13 UTC by jiivan

Part of #1284 

This PR adds following metrics:

1. `market.offers.broadcasts.net` A counter of actual GSB calls
2. `market.offers.broadcasts.net_errors` A counter of actual GSB calls that failed
3. `market.offers.unsubscribes.broadcasts.net` as above with unsubscribes
4. `market.offers.unsubscribes.broadcasts.net_errors` as above with unsubscribes
5. `market.offers.incoming.time` time used to handle incoming offers
6. `market.offers.unsubscribes.incoming.time`

2021-04-29 23:05 UTC, tworec requested changes

2021-04-29 23:05 UTC, tworec commented on core/market/src/protocol/discovery.rs
> +        counter!("market.offers.unsubscribes.broadcasts.net", 1);
I'd also report a histogram (`value!()`) for number of unsubscribes bcasted (`offer_ids.len()`)
```suggestion
        counter!("market.offers.unsubscribes.broadcasts.net", 1);
        value!("market.offers.unsubscribes.broadcasts.size", offer_ids.len());
```

2021-04-30 10:53 UTC, tworec approved these changes

2021-04-30 10:53 UTC, tworec commented on core/market/src/protocol/discovery.rs
> +                    "market.offers.incoming.get_remote.time",
👍

2021-04-30 10:55 UTC, tworec commented
This needs to target `release/v0.6` branch.
I'd also simplify counter names:
- remove`.net` suffix
- change `.net_errors` into `.errors`

2021-04-30 11:04 UTC, tworec requested changes
pls address above comment

2021-04-30 11:11 UTC, jiivan commented
> This needs to target `release/v0.6` branch.
> I'd also simplify counter names:
> 
>     * remove`.net` suffix
There is already such a metric, but it's implemented before queue, so it doesn't reflect actual GSB broadcast calls.

https://github.com/golemfactory/yagna/blob/b71ac703447d86b36ff4a1f32f07bcc6c5fcf2af/core/market/src/matcher/cyclic.rs#L43-L44

2021-04-30 14:06 UTC, tworec approved these changes

2021-04-30 14:25 UTC, merged