Retry transaction in case of invalid nonce
golemfactory/yagna pull request #1566
Opened 2021-08-12 16:34 UTC by nieznanysprawiciel

2021-08-13 08:50 UTC, tworec requested changes
I think we should check zkSync nonce error msg more strictly.
+ minor err msgs tweaks proposed.

2021-08-13 08:50 UTC, tworec commented on core/payment-driver/zksync/src/dao.rs
> +                "Failed to update transaction state in `transaction` {:?} : {:?}",
```suggestion
                "Failed to set status to Created for tx {:?} : {:?}",
```

2021-08-13 08:50 UTC, tworec commented on core/payment-driver/zksync/src/driver.rs
> +                    if err.contains("nonce") {
I'd say that the safest would be to check some error code, but not sure if there are error codes standardized.
To be sure, I'd recommend more strict check here
```suggestion
                    if err.contains("Nonce mismatch") {
```

2021-08-13 08:50 UTC, tworec commented on core/payment-driver/zksync/src/driver.rs
> +                            will be retied. tx_details={:?} error={}",
```suggestion
                            "Scheduling retry for tx {:?} because of nonce mismatch. ZkSync error: {}",
```

2021-08-13 08:50 UTC, tworec commented on core/payment-driver/zksync/src/dao.rs
> +                "Failed to retry transaction in `payment` {:?} : {:?}",
```suggestion
                "Failed to set status of the `payment` {:?} to be retried : {:?}",
```

2021-08-13 09:22 UTC, maaktweluit reviewed
LGTM!

One small comment about tx-status, will approve after that is resolved :)

2021-08-13 09:22 UTC, maaktweluit commented on core/payment-driver/zksync/src/driver.rs
> +                        self.dao.retry_transaction(&tx.tx_id).await;
There is no need to re-try the transaction, since the current transaction just failed.

Only the payments need the state updated to `_NOT_YET`.

2021-08-13 11:01 UTC, maaktweluit commented on core/payment-driver/zksync/src/driver.rs
> +                        self.dao.transaction_failed(&tx.tx_id).await;
this line should still be moved out of the if/else, now the transaction will remain in pending state on nonce failure

2021-08-13 17:26 UTC, tworec approved these changes
lgtm

2021-08-13 18:01 UTC, tworec requested changes
Retarget to `release/v0.7`

2021-08-13 21:50 UTC, tworec submitted a review, later dismissed

2021-08-16 08:29 UTC, tworec approved these changes

2021-08-16 09:28 UTC, mfranciszkiewicz approved these changes

2021-08-18 10:32 UTC, merged