Use released goth 0.6.5
golemfactory/yagna pull request #1589
Opened 2021-09-07 09:24 UTC by filipgolem

2021-09-07 10:20 UTC, zakaprov requested changes
This won't work: this version of `goth` does not include https://github.com/golemfactory/goth/pull/543 which is required for custom usage counters testing. I can make a patch release to include it, though the end result would be the same as using the branch `mf/test-counters` directly.

I'd suggest postponing this change until the next minor release of `goth` (i.e. `0.7.0`) which is going to be compatible with `yagna` version `0.8+`.

2021-09-07 10:20 UTC, zakaprov commented on goth_tests/pyproject.toml
> +goth = "^0.6.5"
```suggestion
goth = "^0.6"
```

2021-09-07 10:20 UTC, mfranciszkiewicz requested changes
- `master` contains tests for custom usage counters
- `goth` 0.6.5 does not include the runtime for testing custom usage counters

`mf/test-counters` has been merged to master (commit 3326ad40f733b731bae50bbc332d9ba5ac558b78)

2021-09-17 08:08 UTC, mfranciszkiewicz commented
Closing in favor of https://github.com/golemfactory/yagna/pull/1592

2021-09-17 08:08 UTC, closed without merging