2327 certificate chain in demand
golemfactory/yagna pull request #2334
Opened 2022-11-24 09:21 UTC by pwalski

Resolves [#2327](https://github.com/golemfactory/yagna/issues/2327)

2022-11-24 12:11 UTC, wkargul requested changes
just a typo and you are ready for merge

2022-11-24 12:11 UTC, wkargul commented on utils/manifest-utils/src/policy.rs
> +        // Demands do not cantain certificates permissions
```suggestion
        // Demands do not contain certificates permissions
```

2022-11-24 12:15 UTC, wkargul approved these changes

2022-11-25 11:02 UTC, evik42 submitted a review, later dismissed
Approving the rebase.

2022-11-25 11:03 UTC, wkargul approved these changes

2022-11-25 11:33 UTC, wkargul approved these changes

2022-11-25 11:40 UTC, evik42 approved these changes

2022-11-25 13:26 UTC, merged