drop id skeleton
golemfactory/yagna pull request #2816
Opened 2023-10-04 11:06 UTC by staszek-krotki

2023-10-04 11:45 UTC, prekucki commented
resolves: #455

2023-10-06 10:15 UTC, nieznanysprawiciel requested changes
It is not enough to mark identity in database. Other services in yagna might use it.
For example payment module signs transactions and probably should be notified. What happens If you remove identity during task computations? I'm not sure about consequences, but probably we will not be able to sign new transactions.

Hybrid Net module has services vector that stores identity prefixed paths.
And it uses default identity to identify itself in the network. So if we removed default identity. we might have unexpected consequences.

There is authentication middleware, that probably caches identities.

If we remove identity what should happen to app-keys created for this identity? If they should be removed than we have cors middleware, that caches app-keys information.

Dropping identity is not trivial problem and that why it wasn't implemented yet.
Last attempt is here: https://github.com/golemfactory/yagna/pull/1537

2023-10-09 08:23 UTC, kamirr commented
> I'm not sure about consequences, but probably we will not be able to sign new transactions.

That is correct. The new payment driver will handle the error somewhat gracefully, but we obviously don't have a copy of the private key and would fail while signing subsequent transactions.

I think a good approach would be to broadcast the intent to remove an `X` identity and only proceed if no subsystems object. The payment driver, for example, would prevent removal of a key that has pending payments. Adding a REST endpoint for that as well would allow the agent to object as well.

2024-02-02 14:57 UTC, prekucki submitted a review, later dismissed

2024-02-02 16:24 UTC, merged