[exe-unit] Single process killing
golemfactory/yagna pull request #488
Opened 2020-08-18 13:51 UTC by boryspoplawski

These changes are needed to run Yagna in Graphene-SGX, which currently does not fully support `/proc` subsystem (used by `ProcessTree`).

2020-08-18 20:46 UTC, mfranciszkiewicz requested changes
Please don't remove `ChildProcess::Tree` and make it feature-enabled in the following fashion:

```rust
enum ChildProcess {
    #[cfg(feature = "sgx")]
    Single { pid: u32 },
    #[cfg(not(feature = "sgx"))]
    Tree(process::ProcessTree),		     
    Service(ProcessService)
}
```

or

```rust
enum ChildProcess {
    #[cfg(feature = "sgx")]
    Subprocess { pid: u32 },
    #[cfg(not(feature = "sgx"))]
    Subprocess { tree: process::ProcessTree },		     
    Service(ProcessService)
}
```

2020-08-18 20:46 UTC, mfranciszkiewicz commented on exe-unit/src/runtime/process.rs
> +            let signle_child = child.id();
typo in `single_child`

2020-08-18 22:21 UTC, boryspoplawski commented
> Please don't remove `ChildProcess::Tree` and [...]

What's the use of `ProcessTree` here? Seems that it always contains a single process anyway ...

2020-08-18 22:22 UTC, boryspoplawski commented on exe-unit/src/runtime/process.rs
> +            let signle_child = child.id();
Done.

2020-08-19 06:01 UTC, mfranciszkiewicz commented
> > Please don't remove `ChildProcess::Tree` and [...]
> 
> What's the use of `ProcessTree` here? Seems that it always contains a single process anyway ...

We're not limiting runtimes to a single process. Replacing `ProcessTree` with `Single` is like reverting to a pre-poc implementation, which shouldn't be done on a whim

2020-08-19 11:54 UTC, boryspoplawski commented
> We're not limiting runtimes to a single process. Replacing `ProcessTree` with `Single` is like reverting to a pre-poc implementation, which shouldn't be done on a whim

I missed that `ProcessTree` iterates through all system processes.
Done.

2020-08-20 06:52 UTC, mfranciszkiewicz approved these changes

2020-08-20 10:36 UTC, merged