TerminateAgreement endpoint
golemfactory/yagna pull request #832
Opened 2020-11-26 11:35 UTC by jiivan

fixes: #727

(just a branch name change from #792 to trigger market tests)

2020-11-26 13:02 UTC, nieznanysprawiciel requested changes
I realized that we can't distinguish between Provider and Requestor Agreement in REST endpoints (as in GetAgreement), but here the problem is much bigger, because we have to know it, to fill `terminator` field in `AgreementTerminatedEvent`. Bu the way note, that we broke GetAgreement endpoint by adding AppSessionId.
I'm afraid we have to address these issues on specification level. @tworec

2020-12-04 10:24 UTC, jiivan commented on core/market/src/negotiation/common.rs
> +            .map_err(|_e| RemoteAgreementError::InternalError(err_msg.agreement_id.clone()))?;
[from chat]: Error is not leaked, but it should be logged locally.

2020-12-04 11:58 UTC, nieznanysprawiciel commented on core/market/src/negotiation/common.rs
> +}
```suggestion
fn verify_reason(reason: Option<&String>) -> Result<(), ReasonError> {
    reason.map(|reason| serde_json::from_str::<Reason>(reason)?);
}
```

2020-12-04 12:09 UTC, nieznanysprawiciel commented on core/market/src/negotiation/common.rs
> +    };
```suggestion
    if let Some(s) = reason {
        serde_json::from_str::<Reason>(s)?
    };
```

2020-12-04 15:56 UTC, nieznanysprawiciel commented on core/market/src/negotiation/common.rs
> +                log::info!(
I would say it is even `warn`, because it would leave Provider and Requestor in inconsistent state

2020-12-07 13:06 UTC, nieznanysprawiciel commented on core/market/src/negotiation/common.rs
> +    };
Or even:
```
    Ok(if let Some(s) = reason {
        serde_json::from_str::<Reason>(s)?;
    })
```

2020-12-07 15:00 UTC, nieznanysprawiciel commented on core/market/src/negotiation/common.rs
> +            "Getting agreement. id: {:?}, agrid: {}, reason: {:?}",
Please don't display using debug if it is possible

2020-12-07 15:05 UTC, nieznanysprawiciel submitted a review, later dismissed

2020-12-07 15:11 UTC, nieznanysprawiciel approved these changes

2020-12-08 08:56 UTC, merged