Add enter / exit / transfer commands to CLI
golemfactory/yagna pull request #931
Opened 2021-01-18 11:02 UTC by maaktweluit

Add CLI commands, GSB messages and driver implementation stubs for:

```
yagna payment enter --driver=zksync --network=rinkeby
yagna payment exit --driver=zksync --network=rinkeby [optional address]
yagna payment transfer —driver=zksync —network=rinkeby [address]
```

2021-01-18 11:18 UTC, Wiezzel requested changes
Parsing amount should be done in CLI, not in driver.

2021-01-18 11:18 UTC, Wiezzel commented on core/model/src/driver.rs
> +    amount: String,
Parsing amount should be done in CLI, not in driver.
```suggestion
    amount: BigDecimal,
```

2021-01-18 11:18 UTC, Wiezzel commented on core/model/src/driver.rs
> +    amount: Option<String>,
Parsing amount should be done in CLI, not in driver.

```suggestion
    amount: Option<BigDecimal>,
```

2021-01-18 11:18 UTC, Wiezzel commented on core/model/src/driver.rs
> +        amount: Option<String>,
Parsing amount should be done in CLI, not in driver.
```suggestion
        amount: Option<BigDecimal>,
```

2021-01-18 11:18 UTC, Wiezzel commented on core/model/src/driver.rs
> +    amount: String,
Parsing amount should be done in CLI, not in driver.
```suggestion
    amount: BigDecimal,
```

2021-01-18 11:18 UTC, Wiezzel commented on core/model/src/driver.rs
> +    pub fn new(amount: String, network: Option<String>, token: Option<String>) -> Enter {
Parsing amount should be done in CLI, not in driver.
```suggestion
    pub fn new(amount: BigDecimal, network: Option<String>, token: Option<String>) -> Enter {
```

2021-01-18 11:18 UTC, Wiezzel commented on core/model/src/driver.rs
> +        amount: String,
Parsing amount should be done in CLI, not in driver.
```suggestion
        amount: BigDecimal,
```

2021-01-18 11:18 UTC, Wiezzel commented on core/payment/src/wallet.rs
> +    amount: String,
Parsing amount should be done in CLI, not in driver.
```suggestion
    amount: BigDecimal,
```

2021-01-18 11:18 UTC, Wiezzel commented on core/payment/src/wallet.rs
> +    amount: Option<String>,
Parsing amount should be done in CLI, not in driver.
```suggestion
    amount: Option<BigDecimal>,
```

2021-01-18 11:18 UTC, Wiezzel commented on core/payment/src/wallet.rs
> +    amount: String,
Parsing amount should be done in CLI, not in driver.
```suggestion
    amount: BigDeciaml,
```

2021-01-18 11:23 UTC, maaktweluit commented
@Wiezzel Was unsure about amount, since it will be put into a string when send over GSB anyhow...

Will update it to parse earlier :)

2021-01-18 14:32 UTC, Wiezzel approved these changes

2021-01-19 06:53 UTC, pnowosie approved these changes
Great work!

2021-01-19 10:30 UTC, merged