report yagna version as metrics
golemfactory/yagna pull request #933
Opened 2021-01-18 15:34 UTC by etam

closes #838

2021-01-19 12:29 UTC, etam commented
waiting for #937 #938

2021-01-19 14:38 UTC, tworec requested changes

2021-01-20 11:19 UTC, etam commented on utils/compile-time-utils/src/lib.rs
> +        // should not panic
My thinking was that if someone does this intentionally, then failure in test should tell them to not do it. Same with tagging.
But I can relax this requirement and handle nonconforming env variables.

2021-01-21 02:14 UTC, tworec approved these changes

2021-01-21 03:08 UTC, merged